# GENERATED CODE -- Lambda2 residual of Lambda-CCSDT, machine-generated
# using the P(x,y) antisymmetrizer / index-letter conventions described
# below. Do not edit by hand. Output shape (nv, nv, no, no) -- see solver.py for
# why it is transposed before use.
import numpy as np

from .cached_einsum import einsum
from .parallel_accum import pacc


def lambda2_residual(t1, t2, t3, l1, l2, l3, f, g, o, v):
    nv, no = t1.shape
    lambda2_res = np.zeros((nv, nv, no, no))
    pacc(lambda2_res, ((1.00, einsum('mnef->efnm', g[o, o, v, v])),))
    contracted_intermediate = -1.00 * einsum('ne,mf->efnm', f[o, v], l1)
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (1.00000, einsum('efnm->femn', contracted_intermediate)),))
    contracted_intermediate = -1.00 * einsum('ni,mief->efnm', f[o, o], l2)
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    contracted_intermediate =  1.00 * einsum('ae,mnaf->efnm', f[v, v], l2)
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate =  1.00 * einsum('ie,ai,mnfa->efnm', f[o, v], t1, l2, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate =  1.00 * einsum('na,ai,imef->efnm', f[o, v], t1, l2, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    contracted_intermediate = -0.50 * einsum('je,baij,imnfba->efnm', f[o, v], t2, l3, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate = -0.50 * einsum('nb,baij,ijmefa->efnm', f[o, v], t2, l3, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    contracted_intermediate = -1.00 * einsum('mnei,if->efnm', g[o, o, v, o], l1)
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate = -1.00 * einsum('naef,ma->efnm', g[o, v, v, v], l1)
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (0.50, einsum('mnij,ijef->efnm', g[o, o, o, o], l2)),))
    contracted_intermediate =  1.00 * einsum('naei,miaf->efnm', g[o, v, v, o], l2)
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (1.00000, einsum('efnm->femn', contracted_intermediate)),))
    pacc(lambda2_res, ((0.50, einsum('baef,mnba->efnm', g[v, v, v, v], l2)),))
    contracted_intermediate = -0.50 * einsum('naij,mijaef->efnm', g[o, v, o, o], l3)
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    contracted_intermediate = -0.50 * einsum('baei,mnibaf->efnm', g[v, v, v, o], l3)
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate = -1.00 * einsum('inef,ai,ma->efnm', g[o, o, v, v], t1, l1, optimize=['einsum_path', (1, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    contracted_intermediate = -1.00 * einsum('mnea,ai,if->efnm', g[o, o, v, v], t1, l1, optimize=['einsum_path', (1, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate =  1.00 * einsum('inea,ai,mf->efnm', g[o, o, v, v], t1, l1, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (1.00000, einsum('efnm->femn', contracted_intermediate)),))
    contracted_intermediate = -1.00 * einsum('jnei,aj,mifa->efnm', g[o, o, v, o], t1, l2, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (1.00000, einsum('efnm->femn', contracted_intermediate)),))
    pacc(lambda2_res, ((1.00, einsum('mnaj,ai,ijef->efnm', g[o, o, v, o], t1, l2, optimize=['einsum_path', (0, 1), (0, 1)])),))
    contracted_intermediate = -1.00 * einsum('jnai,aj,mief->efnm', g[o, o, v, o], t1, l2, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (1.00, einsum('ibef,ai,mnba->efnm', g[o, v, v, v], t1, l2, optimize=['einsum_path', (0, 1), (0, 1)])),))
    contracted_intermediate = -1.00 * einsum('naeb,bi,imaf->efnm', g[o, v, v, v], t1, l2, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (1.00000, einsum('efnm->femn', contracted_intermediate)),))
    contracted_intermediate = -1.00 * einsum('iaeb,bi,mnaf->efnm', g[o, v, v, v], t1, l2, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate = -0.50 * einsum('knij,ak,mijefa->efnm', g[o, o, o, o], t1, l3, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    contracted_intermediate =  1.00 * einsum('jbei,aj,mnibfa->efnm', g[o, v, v, o], t1, l3, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate =  1.00 * einsum('nabj,bi,imjaef->efnm', g[o, v, v, o], t1, l3, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    contracted_intermediate = -0.50 * einsum('baec,ci,imnbaf->efnm', g[v, v, v, v], t1, l3, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate = -0.50 * einsum('jnef,baij,imba->efnm', g[o, o, v, v], t2, l2, optimize=['einsum_path', (1, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (0.250, einsum('jief,baji,mnba->efnm', g[o, o, v, v], t2, l2, optimize=['einsum_path', (0, 1), (0, 1)])),))
    contracted_intermediate = -0.50 * einsum('mneb,baij,ijfa->efnm', g[o, o, v, v], t2, l2, optimize=['einsum_path', (1, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate =  1.00 * einsum('jneb,baij,imfa->efnm', g[o, o, v, v], t2, l2, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (1.00000, einsum('efnm->femn', contracted_intermediate)),))
    contracted_intermediate = -0.50 * einsum('jieb,baji,mnfa->efnm', g[o, o, v, v], t2, l2, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (0.250, einsum('mnab,abij,ijef->efnm', g[o, o, v, v], t2, l2, optimize=['einsum_path', (0, 1), (0, 1)])),))
    contracted_intermediate = -0.50 * einsum('jnab,abij,imef->efnm', g[o, o, v, v], t2, l2, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    contracted_intermediate =  0.50 * einsum('knej,baik,imjfba->efnm', g[o, o, v, o], t2, l3, optimize=['einsum_path', (1, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (1.00000, einsum('efnm->femn', contracted_intermediate)),))
    contracted_intermediate = -0.250 * einsum('kjei,bakj,mnifba->efnm', g[o, o, v, o], t2, l3, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (-0.50, einsum('mnbk,baij,ijkefa->efnm', g[o, o, v, o], t2, l3, optimize=['einsum_path', (1, 2), (0, 1)])),))
    contracted_intermediate =  1.00 * einsum('knbj,baik,imjefa->efnm', g[o, o, v, o], t2, l3, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (-0.50, einsum('jcef,baij,imncba->efnm', g[o, v, v, v], t2, l3, optimize=['einsum_path', (1, 2), (0, 1)])),))
    contracted_intermediate =  0.50 * einsum('nbec,caij,ijmbfa->efnm', g[o, v, v, v], t2, l3, optimize=['einsum_path', (1, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (1.00000, einsum('efnm->femn', contracted_intermediate)),))
    contracted_intermediate =  1.00 * einsum('jbec,caij,imnbfa->efnm', g[o, v, v, v], t2, l3, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate = -0.250 * einsum('nabc,bcij,ijmaef->efnm', g[o, v, v, v], t2, l3, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    contracted_intermediate = -0.083333333333333 * einsum('knef,cbaijk,ijmcba->efnm', g[o, o, v, v], t3, l3, optimize=['einsum_path', (1, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (0.083333333333333, einsum('kjef,cbaikj,imncba->efnm', g[o, o, v, v], t3, l3, optimize=['einsum_path', (1, 2), (0, 1)])),))
    contracted_intermediate = -0.083333333333333 * einsum('mnec,cbaijk,ijkfba->efnm', g[o, o, v, v], t3, l3, optimize=['einsum_path', (1, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate =  0.250 * einsum('knec,cbaijk,ijmfba->efnm', g[o, o, v, v], t3, l3, optimize=['einsum_path', (1, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (1.00000, einsum('efnm->femn', contracted_intermediate)),))
    contracted_intermediate = -0.250 * einsum('kjec,cbaikj,imnfba->efnm', g[o, o, v, v], t3, l3, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (0.083333333333333, einsum('mnbc,bcaijk,ijkefa->efnm', g[o, o, v, v], t3, l3, optimize=['einsum_path', (1, 2), (0, 1)])),))
    contracted_intermediate = -0.250 * einsum('knbc,bcaijk,ijmefa->efnm', g[o, o, v, v], t3, l3, optimize=['einsum_path', (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (0.50, einsum('kjef,baik,cj,imncba->efnm', g[o, o, v, v], t2, t1, l3, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])),))
    contracted_intermediate = -0.50 * einsum('knec,baik,cj,ijmfba->efnm', g[o, o, v, v], t2, t1, l3, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (1.00000, einsum('efnm->femn', contracted_intermediate)),))
    contracted_intermediate = -0.50 * einsum('knec,caij,bk,ijmfba->efnm', g[o, o, v, v], t2, t1, l3, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (1.00000, einsum('efnm->femn', contracted_intermediate)),))
    contracted_intermediate = -0.50 * einsum('kjec,baik,cj,imnfba->efnm', g[o, o, v, v], t2, t1, l3, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate = -0.250 * einsum('kjec,bakj,ci,imnfba->efnm', g[o, o, v, v], t2, t1, l3, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate =  1.00 * einsum('kjec,caik,bj,imnfba->efnm', g[o, o, v, v], t2, t1, l3, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (0.50, einsum('mnbc,caij,bk,ijkefa->efnm', g[o, o, v, v], t2, t1, l3, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])),))
    contracted_intermediate = -0.50 * einsum('knbc,caij,bk,ijmefa->efnm', g[o, o, v, v], t2, t1, l3, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    contracted_intermediate =  1.00 * einsum('knbc,caik,bj,ijmefa->efnm', g[o, o, v, v], t2, t1, l3, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    contracted_intermediate = -0.250 * einsum('knbc,ak,bcij,ijmefa->efnm', g[o, o, v, v], t1, t2, l3, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (-0.50, einsum('jief,aj,bi,mnba->efnm', g[o, o, v, v], t1, t1, l2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])),))
    contracted_intermediate =  1.00 * einsum('jneb,aj,bi,imfa->efnm', g[o, o, v, v], t1, t1, l2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (1.00000, einsum('efnm->femn', contracted_intermediate)),))
    contracted_intermediate =  1.00 * einsum('jieb,aj,bi,mnfa->efnm', g[o, o, v, v], t1, t1, l2, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)), (-0.50, einsum('mnab,aj,bi,ijef->efnm', g[o, o, v, v], t1, t1, l2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])),))
    contracted_intermediate =  1.00 * einsum('jnab,aj,bi,imef->efnm', g[o, o, v, v], t1, t1, l2, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    contracted_intermediate =  0.50 * einsum('kjei,ak,bj,mnifba->efnm', g[o, o, v, o], t1, t1, l3, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate =  1.00 * einsum('knbj,ak,bi,imjefa->efnm', g[o, o, v, o], t1, t1, l3, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    contracted_intermediate =  1.00 * einsum('jbec,aj,ci,imnbfa->efnm', g[o, v, v, v], t1, t1, l3, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate =  0.50 * einsum('nabc,bj,ci,ijmaef->efnm', g[o, v, v, v], t1, t1, l3, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    contracted_intermediate =  0.50 * einsum('kjec,ak,bj,ci,imnfba->efnm', g[o, o, v, v], t1, t1, t1, l3, optimize=['einsum_path', (0, 1), (0, 3), (0, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->fenm', contracted_intermediate)),))
    contracted_intermediate =  0.50 * einsum('knbc,ak,bj,ci,ijmefa->efnm', g[o, o, v, v], t1, t1, t1, l3, optimize=['einsum_path', (0, 1), (0, 3), (0, 2), (0, 1)])
    pacc(lambda2_res, ((1.00000, contracted_intermediate), (-1.00000, einsum('efnm->efmn', contracted_intermediate)),))
    return lambda2_res
